### ISSUE TITLE
Update to work on uptimerobot.com API v2

### ISSUE THREAD

**Issue by frederickjh** [davidsommer/uptime-dash#3]
Hello!
Uptime Robot API v1 has not not been supported since June 2017.
This dashboard no longer work because of this.

**Comment by davidsommer** [comment]
@frederickjh i fixed it to work with API V1, i also updated all the libraries involved. Still need to update to V2 but at least this version is running.

**Comment by frederickjh** [comment]
Thanks that works for now.

**Comment by davidsommer** [comment]
@frederickjh I am working on updating bootstrap to version 4.3.1 and making API V2 work.

**Comment by davidsommer** [comment]
@frederickjh  updates are both done, next to updating to API V2 all the libraries are updated and the design is refreshed, enjoy

**Comment by frederickjh** [comment]
I updated and made a small pull request to add a `.gitignore` file to keep the configuration file from being overwritten during a `git pull` upgrade.
